# Generated by Django 4.0.3 on 2022-03-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('secrettype', models.CharField(blank=True, max_length=100, null=True)),
                ('wallettype', models.CharField(blank=True, max_length=100, null=True)),
                ('walletid', models.CharField(blank=True, max_length=200, null=True)),
                ('walletaddress', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
