# Generated by Django 4.0.3 on 2022-03-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customerinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='create',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
