# Generated by Django 4.0.3 on 2022-03-23 05:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customerinfo_create'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinfo',
            name='create',
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='creating',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
