# Generated by Django 4.0.3 on 2022-03-25 01:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_imagecontractnft_applicationid'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecontractnft',
            name='contract_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagecontractnft',
            name='hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='imagecontractnft',
            name='symbol',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
