# Generated by Django 4.0.3 on 2022-03-25 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_imagecontractnft_contract_id_imagecontractnft_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecontractnft',
            name='contract_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
