# Generated by Django 4.0.3 on 2022-03-25 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_imagecontractnft_contracts_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagecontractnft',
            name='contract_id',
        ),
    ]
