# Generated by Django 4.0.3 on 2022-03-25 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_imagecontractnft_contracts_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecontractnft',
            name='contracts_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
