# Generated by Django 4.0.3 on 2022-03-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_fungibletoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='MintNft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('application_id', models.CharField(blank=True, max_length=100, null=True)),
                ('contract_id', models.CharField(blank=True, max_length=100, null=True)),
                ('token_id', models.CharField(blank=True, max_length=100, null=True)),
                ('destination', models.CharField(blank=True, max_length=100, null=True)),
                ('supply', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
