# Generated by Django 4.0.3 on 2022-04-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='appsid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
