# Generated by Django 4.0.3 on 2022-03-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_imagecontractnft_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecontractnft',
            name='applicationId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
