# Generated by Django 4.0.3 on 2022-03-25 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_imagecontractnft_contract_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecontractnft',
            name='contracts_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
