# Generated by Django 4.0.3 on 2022-03-25 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_imagecontractnft_contract_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecontractnft',
            name='contracts_id',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
