# Generated by Django 4.0.3 on 2022-03-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_imagecontractnft_contracts_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecontractnft',
            name='owner_name',
            field=models.TextField(blank=True),
        ),
    ]
