# Generated by Django 4.0.3 on 2022-03-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_imagecontractnft_owner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecontractnft',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
