# Generated by Django 4.0.3 on 2022-03-29 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_imagecontractnft_owner_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenTypeNft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_token', models.CharField(blank=True, max_length=100, null=True)),
                ('token_image', models.ImageField(upload_to='ttImages/%Y/%m/%d/')),
                ('contract_id_token', models.CharField(blank=True, max_length=100, null=True)),
                ('appsid_token', models.CharField(blank=True, max_length=100, null=True)),
                ('site_url', models.CharField(blank=True, max_length=100, null=True)),
                ('token_type_att', models.CharField(blank=True, max_length=100, null=True)),
                ('token_name_att', models.CharField(blank=True, max_length=100, null=True)),
                ('token_value_att', models.CharField(blank=True, max_length=100, null=True)),
                ('token_description', models.CharField(blank=True, max_length=100, null=True)),
                ('token_bg', models.CharField(blank=True, max_length=100, null=True)),
                ('token_type', models.CharField(blank=True, max_length=100, null=True)),
                ('token_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('storage_url', models.CharField(blank=True, max_length=100, null=True)),
                ('type_storage', models.CharField(blank=True, max_length=100, null=True)),
                ('thumbnail_url', models.CharField(blank=True, max_length=100, null=True)),
                ('preview_url', models.CharField(blank=True, max_length=100, null=True)),
                ('supply', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
