# Generated by Django 4.0.3 on 2022-03-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_tokentypenft'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokentypenft',
            name='token_owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
