# Generated by Django 4.0.3 on 2022-04-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_mintnft'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='default.png', upload_to='profileImages/%Y/%m/%d/'),
        ),
    ]
